### PR TITLE
#161040962 Login Page

### PR DESCRIPTION
**Pull request by TooColline**
**What does this PR do?**
It Creates a Login page for the Store Attendant and Store Owner.

**Description of Task to be completed?**
The user should be able to log in using a valid Email Address and a Password. If the credentials are incorrect, the user gets an error message to help them out.

**How should this be manually tested?**
Clone the repository to your local machine using the link ```https://github.com/TooColline/Store-Manager.git```. 
Then cd into Store-Manager then templates, then launch login.html on your browser and try it out.

**Background context you want to provide?**
That the Login credentials should be provided and validated before being able to log in.

**What are the relevant pivotal tracker stories?**
#161040962

**Screenshots(if appropriate)**
image

### CODE REVIEW

**Comment by vikitaotiz** [comment]
Nice work

**Comment by Krafty-Coder** [comment]
Nice work.. Neat code,
Haven't seen your responsiveness code.. Hope you don't mind uploading the mobile view of the page

**Comment by TooColline** [comment]
Will work on that. Thank you.

**Comment by winniekariuki** [comment]
Simple and nice page.But I suggest you remove the navigation home,about and login buttons since this is a login page I suppose.

**Comment by TooColline** [comment]
Alright Winnie. Thanks

**Comment by MusyokiBryan** [comment]
Good job it looks great

**Pull request merged**
